# Generated by Django 6.0.1 on 2026-01-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressionsimage',
            name='impressions',
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='airbnb_app.property'),
        ),
        migrations.DeleteModel(
            name='Impressions',
        ),
        migrations.DeleteModel(
            name='ImpressionsImage',
        ),
    ]
